"""
AZALS MODULE M11 - Conformité (Compliance)
==========================================

Module de gestion de la conformité réglementaire et des politiques.
"""

from .models import (
    ActionStatus,
    AssessmentStatus,
    AuditStatus,
    ComplianceAction,
    ComplianceAssessment,
    ComplianceAudit,
    ComplianceAuditFinding,
    ComplianceDocument,
    ComplianceGap,
    ComplianceIncident,
    ComplianceReport,
    ComplianceRisk,
    ComplianceStatus,
    ComplianceTraining,
    DocumentType,
    IncidentSeverity,
    Policy,
    PolicyAcknowledgment,
    Regulation,
    RegulationType,
    ReportType,
    Requirement,
    RequirementPriority,
    RiskLevel,
    TrainingCompletion,
)
from .router_crud import router
from .schemas import (
    AcknowledgmentCreate,
    AcknowledgmentResponse,
    ActionCreate,
    ActionResponse,
    ActionUpdate,
    AssessmentCreate,
    AssessmentResponse,
    AssessmentUpdate,
    AuditCreate,
    AuditResponse,
    AuditUpdate,
    CompletionCreate,
    CompletionResponse,
    ComplianceDashboard,
    ComplianceMetrics,
    DocumentCreate,
    DocumentResponse,
    DocumentUpdate,
    FindingCreate,
    FindingResponse,
    GapCreate,
    GapResponse,
    IncidentCreate,
    IncidentResponse,
    IncidentUpdate,
    PolicyCreate,
    PolicyResponse,
    PolicyUpdate,
    RegulationCreate,
    RegulationResponse,
    RegulationUpdate,
    ReportCreate,
    ReportResponse,
    RequirementCreate,
    RequirementResponse,
    RequirementUpdate,
    RiskCreate,
    RiskResponse,
    RiskUpdate,
    TrainingCreate,
    TrainingResponse,
    TrainingUpdate,
)
from .service import ComplianceService, get_compliance_service

__all__ = [
    # Models
    "Regulation", "Requirement", "ComplianceAssessment", "ComplianceGap",
    "ComplianceAction", "Policy", "PolicyAcknowledgment",
    "ComplianceTraining", "TrainingCompletion",
    "ComplianceDocument", "ComplianceAudit", "ComplianceAuditFinding",
    "ComplianceRisk", "ComplianceIncident", "ComplianceReport",
    # Enums
    "ComplianceStatus", "RegulationType", "RequirementPriority",
    "AssessmentStatus", "RiskLevel", "ActionStatus", "DocumentType",
    "AuditStatus", "IncidentSeverity", "ReportType",
    # Schemas
    "RegulationCreate", "RegulationUpdate", "RegulationResponse",
    "RequirementCreate", "RequirementUpdate", "RequirementResponse",
    "AssessmentCreate", "AssessmentUpdate", "AssessmentResponse",
    "GapCreate", "GapResponse",
    "ActionCreate", "ActionUpdate", "ActionResponse",
    "PolicyCreate", "PolicyUpdate", "PolicyResponse",
    "AcknowledgmentCreate", "AcknowledgmentResponse",
    "TrainingCreate", "TrainingUpdate", "TrainingResponse",
    "CompletionCreate", "CompletionResponse",
    "DocumentCreate", "DocumentUpdate", "DocumentResponse",
    "AuditCreate", "AuditUpdate", "AuditResponse",
    "FindingCreate", "FindingResponse",
    "RiskCreate", "RiskUpdate", "RiskResponse",
    "IncidentCreate", "IncidentUpdate", "IncidentResponse",
    "ReportCreate", "ReportResponse",
    "ComplianceDashboard", "ComplianceMetrics",
    # Service
    "ComplianceService", "get_compliance_service",
    # Router
    "router",
]
