"""
AZALS - Module M10: BI & Reporting
Business Intelligence, Tableaux de bord, KPIs et Rapports
"""

from .models import (
    # Enums
    DashboardType,
    WidgetType,
    ChartType,
    ReportType,
    ReportFormat,
    ReportStatus,
    KPICategory,
    KPITrend,
    AlertSeverity,
    AlertStatus,
    DataSourceType,
    RefreshFrequency,
    # Models
    Dashboard,
    DashboardWidget,
    WidgetFilter,
    Report,
    ReportSchedule,
    ReportExecution,
    KPIDefinition,
    KPIValue,
    KPITarget,
    Alert,
    AlertRule,
    DataSource,
    DataQuery,
    Bookmark,
    ExportHistory,
)

from .schemas import (
    DashboardCreate,
    DashboardUpdate,
    DashboardResponse,
    DashboardList,
    WidgetCreate,
    WidgetUpdate,
    WidgetResponse,
    ReportCreate,
    ReportUpdate,
    ReportResponse,
    ReportList,
    ReportExecutionResponse,
    KPICreate,
    KPIUpdate,
    KPIResponse,
    KPIList,
    KPIValueCreate,
    KPIValueResponse,
    KPITargetCreate,
    KPITargetResponse,
    AlertCreate,
    AlertUpdate,
    AlertResponse,
    AlertList,
    AlertRuleCreate,
    AlertRuleResponse,
    DataSourceCreate,
    DataSourceUpdate,
    DataSourceResponse,
    DataQueryCreate,
    DataQueryResponse,
    BookmarkCreate,
    BookmarkResponse,
    ExportRequest,
    ExportResponse,
    DashboardStats,
    BIOverview,
)

from .service import BIService, get_bi_service

__all__ = [
    # Enums
    "DashboardType",
    "WidgetType",
    "ChartType",
    "ReportType",
    "ReportFormat",
    "ReportStatus",
    "KPICategory",
    "KPITrend",
    "AlertSeverity",
    "AlertStatus",
    "DataSourceType",
    "RefreshFrequency",
    # Models
    "Dashboard",
    "DashboardWidget",
    "WidgetFilter",
    "Report",
    "ReportSchedule",
    "ReportExecution",
    "KPIDefinition",
    "KPIValue",
    "KPITarget",
    "Alert",
    "AlertRule",
    "DataSource",
    "DataQuery",
    "Bookmark",
    "ExportHistory",
    # Schemas
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardResponse",
    "DashboardList",
    "WidgetCreate",
    "WidgetUpdate",
    "WidgetResponse",
    "ReportCreate",
    "ReportUpdate",
    "ReportResponse",
    "ReportList",
    "ReportExecutionResponse",
    "KPICreate",
    "KPIUpdate",
    "KPIResponse",
    "KPIList",
    "KPIValueCreate",
    "KPIValueResponse",
    "KPITargetCreate",
    "KPITargetResponse",
    "AlertCreate",
    "AlertUpdate",
    "AlertResponse",
    "AlertList",
    "AlertRuleCreate",
    "AlertRuleResponse",
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    "DataQueryCreate",
    "DataQueryResponse",
    "BookmarkCreate",
    "BookmarkResponse",
    "ExportRequest",
    "ExportResponse",
    "DashboardStats",
    "BIOverview",
    # Service
    "BIService",
    "get_bi_service",
]
